### ISSUE TITLE
petab_select.Model.to_petab not working

### ISSUE THREAD

**Issue by fbergmann** [PEtab-dev/petab_select#1]
Wanting to try out the package, i've ran into a snag, potentially a wrong petab version. The error message is: 

      petab_select/petab_select/model.py in to_petab(self, output_path)
          330         if output_path is not None:
          331             petab_yaml_path = \
      --> 332                 petab_problem.to_files_generic(prefix_path=output_path)
          333 
          334         return (petab_problem, petab_yaml_path)

maybe it should be `to_files` rather than `to_files_generic`.

**Comment by dilpath** [comment]
Hi Frank, thanks for reporting! Sorry, should be fixed in the latest release of `libpetab-python` (v0.1.20).
