### ISSUE TITLE
Fixed parameters entering as measurements in calculation of AICc

### ISSUE THREAD

**Issue by adrianhauber** [PEtab-dev/petab_select#2]
M1_3 in test case 0004 has 4 parameters in total, of which 2 are fixed during parameter estimation. The expected AICc seems to be calculated for `n_estimated = 2, n_priors = 2` (I guess the comment in l. 127 of [petab_select/criteria.py](https://github.com/PEtab-dev/petab_select/blob/c6bf79cdbd4e07639df3e6da4080a4e34c448a36/petab_select/criteria.py#L127) is related).

From my understanding, it should be either `n_estimated = 2, n_priors = 0` or `n_estimated = 4, n_priors = 2` (consider fixed parameters as estimated ones but with an infinitely narrow prior). However, these two approaches do *not* result in the same criterion. Could somebody elaborate or give a reference on why priors are treated as measurements in the calculation of, e.g., the AICc?

**Comment by dilpath** [comment]
Thanks for reporting this. There was an error in the calculation of the number of priors. In this particular example, it should now match the case `n_estimated = 2, n_priors = 0`.

As for the treatment of priors as measurements, this is done similarly to this paper [1] (Section 4.4); however, a reference is still missing.

[1] https://doi.org/10.1016/j.epidem.2021.100439

**Comment by adrianhauber** [comment]
Thanks for your answer, that makes sense to me.
