### ISSUE TITLE
sbmldocument leaking

### ISSUE THREAD

**Issue by fbergmann** [PEtab-dev/petab_select#43]
Running a basic analysis like: 

```python
    problem = Problem.from_yaml(args.yaml_file_name)
    best = evaluate_problem(problem,
            temp_dir=args.output_dir,
            delete_temp_files=False)

    if args.output_yaml: 
        best.to_yaml(args.output_yaml)
```

where the `evaluate_problem` function is one of mine, not doing anything with libsbml, `Problem` is the petab_select one. Yields a warning message: 

```
swig/python detected a memory leak of type 'SBMLDocument *', no destructor found.
```

**Comment by dweindl** [comment]
Hm, that sounds more like an issue in python-libsbml / swig, doesn't it?

**Comment by dweindl** [comment]
Maybe related to https://github.com/swig/swig/issues/2638

Not a petab_select issue.
