### ISSUE TITLE
Creating candidate space fails for version 0.1.12

### ISSUE THREAD

**Issue by sebapersson** [PEtab-dev/petab_select#82]
For the latest version of petab-select PEtab.jl errors. Running on Python 3.10 it boils down to:

```python
select_problem = petab_select.Problem.from_yaml("petab_select_problem.yaml")
cs = petab_select.ui.candidates(problem=select_problem, criterion=select_problem.criterion)
```

Yielding the error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebpe/anaconda3/envs/PeTab/lib/python3.10/site-packages/petab_select/ui.py", line 99, in candidates
    predecessor_model.get_criterion(
AttributeError: 'NoneType' object has no attribute 'get_criterion'
```

Everything worked prior to version 0.1.12 (noticed this once I managed to get PyCall workng on GitHub CI).

I used the petab-select problem file from [here](https://github.com/PEtab-dev/petab_select/blob/main/test_cases/0001/petab_select_problem.yaml).

**Comment by dilpath** [comment]
Thanks for reporting! This kind of error will be caught when the calibration tests are re-introduced soon.
