### ISSUE TITLE
Prettify/populate sphinx-doc

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/petab_select#95]
https://petab-select.readthedocs.io/en/develop/ still needs some work

- [x] nicer landing page
- [x] petab-select input files #102 
- [x] link to pypesto integration example
- [x] link to other tools supporting petab-select

**Comment by dweindl** [comment]
@dilpath : do you prefer having `File formats` and `Test cases` only on readthedocs, or README+readthedocs?

**Comment by dilpath** [comment]
I would prefer having it on readthedocs only
